### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by webdotorg**
Let me know what you guys think of this new read me. Feel free to make changes. This is kinda what I envision as of now.

### CODE REVIEW

**Comment by Levi-Lesches** [comment]
When you say "search", you mean Google? That'll return billions of results for any company!

**Comment by webdotorg** [comment]
Ya, I considered that as I started typing. Which Is why I said...without looking at the readme--something like "scaling back the results".

I don't know what the best way to do that is.

There's this line between optimizing search results and overwhelming ourselves with data. The question is where is that line.

**Comment by Levi-Lesches** [comment]
I suggest that instead of looking for their presence on the web (aside from social media, which IS important) we examine existing SEO efforts from the site, since [Google's Search Console](https://search.google.com/search-console/) handles search results pretty well already.

**Comment by webdotorg** [comment]
That sounds like a good idea. I doubt we could pool the resources to make our own. However...the "Using Our Services" clause might be an issue in the terms of service. <https://policies.google.com/terms>. 
But before getting ahead of ourselves, let's use Google's SEO Console. We can compile and plot that data or represent it in a bar graph (or both).
Then, figure out the best way to improve search results "automatically". Remember, this is to be end-user friendly.

**Comment by Levi-Lesches** [comment]
You mean the intellectual property part? Yeah, there's only so much snooping we can do without explicit consent. 

BTW we can't use the search console. You need to be a verified owner of the website to do so.

**Comment by Levi-Lesches** [comment]
We should really focus on just what we can access, such as HTML and social media presence

**Pull request merged**
